### ISSUE TITLE
How to insert HTML into the template

### ISSUE THREAD

**Issue by hmsvitor** [janmarkuslanger/attention.js#1]
When I try to add HTML tags on the confirm's body, it print the tags and not execute them.

If I can't format the body of the alert/confirm/prompt with HTML tags, how can I do it ?

**Comment by janmarkuslanger** [comment]
HEy @hmsivxx can you show me the code you wrote?

**Comment by hmsivxx** [comment]
something like this:

` document.querySelector('.new-confirm').addEventListener('click', function() {
                new Attention.Confirm({
                    title: 'Nice confirm',
                    content: `
                        <b>Field_1:</b>${field1} <br>
                        <b>Field_2:</b>${field2} <br>
                        <b>Field_3:</b>${field3} <br>
                        <b>Field_4:</b>${field4} <br>
                        <b>Field_5:</b>${field5}
                    `,
                    onCancel: function(component) {
                        demo.innerHTML += '<h4>Confirm was canceled</h4>';
                    },
                    onConfirm: function(component) {
                        demo.innerHTML += '<h4>Confirm was accepted</h4>';
                    }
                });
            });`

**Comment by hmsivxx** [comment]
something like this:

 document.querySelector('.new-confirm').addEventListener('click', function() {
                new Attention.Confirm({
                    title: 'Nice confirm',
                    content: `
                        <b>Field_1:</b>${field1} <br>
                        <b>Field_2:</b>${field2} <br>
                        <b>Field_3:</b>${field3} <br>
                        <b>Field_4:</b>${field4} <br>
                        <b>Field_5:</b>${field5}
                    `,
                    onCancel: function(component) {
                        demo.innerHTML += '<h4>Confirm was canceled</h4>';
                    },
                    onConfirm: function(component) {
                        demo.innerHTML += '<h4>Confirm was accepted</h4>';
                    }
                });
            });

**Comment by hmsvitor** [comment]
something like this:

```javascript
 document.querySelector('.new-confirm').addEventListener('click', function() {
                new Attention.Confirm({
                    title: 'Nice confirm',
                    content: `
                        <b>Field_1:</b>${field1} <br>
                        <b>Field_2:</b>${field2} <br>
                        <b>Field_3:</b>${field3} <br>
                        <b>Field_4:</b>${field4} <br>
                        <b>Field_5:</b>${field5}
                    `,
                    onCancel: function(component) {
                        demo.innerHTML += '<h4>Confirm was canceled</h4>';
                    },
                    onConfirm: function(component) {
                        demo.innerHTML += '<h4>Confirm was accepted</h4>';
                    }
                });
            });
```

**Comment by janmarkuslanger** [comment]
@hmsivxx if you pass your content via the content key. The content will not be inserted with innerHTML. Take a look at this gist. https://gist.github.com/janmarkuslanger/f758e2d6006b46b937084bb51d88feeb
Maybe it helps you. If you still need help. Let me know :)

**Comment by janmarkuslanger** [comment]
@hmsivxx does it help you?

**Comment by hmsvitor** [comment]
I'll check it out and let you know

**Comment by janmarkuslanger** [comment]
@hmsivxx thank you

**Comment by hmsvitor** [comment]
I still couldn't make it to work.

I am trying to render HTML tags on the body of the alert/confirm/prompt

```javascript
new Attention.Alert({
                    title: 'Nice alert!',
                    content: 'I need to render HTML tags here',
                    beforeRender(component) {
                    component.template.innerHTML = '<h2>sdfasd</h2>';
                    }
                });
```

This is rendering the HTML on the page, not really on the body of the popup.

**Comment by janmarkuslanger** [comment]
@hmsivxx I worked on that. Download a new version. Let me know if this works for you. 

``` javascript
new Attention.Confirm({
  title: 'Nice confirm',
  content: '<h1>This is my content</h1>',
  useInnerHTML: true
});
```

**Comment by hmsvitor** [comment]
I don't really know why, but it isn't working here yet

![image](https://user-images.githubusercontent.com/49028929/64348723-11c65780-cfcc-11e9-8e26-fc75a0e102ec.png)

**Comment by janmarkuslanger** [comment]
@hmsivxx how did you install attention.js? Did you download the newest version?

**Comment by hmsvitor** [comment]
yes, I downloaded a zip file with the new version

**Comment by janmarkuslanger** [comment]
Can you show me the console? Is there an error?

**Comment by janmarkuslanger** [comment]
@hmsivxx and did you use `useInnerHTML: true` ?

**Comment by hmsvitor** [comment]
I just tested here at home and it worked!

I will see tomorrow in the office why it didn't work.

Thanks for your support!

**Comment by janmarkuslanger** [comment]
@hmsivxx you´re welcome! I close this issue. If there is still a problem feel free to reopen this.
