### ISSUE TITLE
How can I use this in my angular app?

### ISSUE THREAD

**Issue by Ros4eva** [janmarkuslanger/attention.js#2]
Hi Mark, is a wonderful you have here but am having adding it to my angular app.
How do I import it as a module on my angular app?

**Comment by janmarkuslanger** [comment]
Thank you for your contribution!

**Comment by janmarkuslanger** [comment]
@Ros4eva hey there, 

thank you for using attention.js. I will take a look at your issue and coming back to you soon. 
Which version do you use?

**Comment by Ros4eva** [comment]
thank you for the quick response.
Am using Angular 7

**Comment by janmarkuslanger** [comment]
Hey @Ros4eva 

maybe this link will help you. :) 
https://hackernoon.com/how-to-use-javascript-libraries-in-angular-2-apps-ff274ba601af

If you need additional help, please contact me.

**Comment by janmarkuslanger** [comment]
@Ros4eva anything new? I will close this otherwise.
