### ISSUE TITLE
Error while trying to create a prompt window using vuejs

### ISSUE THREAD

**Issue by metroidpam** [janmarkuslanger/attention.js#3]
![image](https://user-images.githubusercontent.com/4321428/91580493-7a30e600-e94d-11ea-9483-9ec79d198073.png)

`restock:function(item){
	    new Attention.Prompt({
		title: 'Quantité de ' + item.item_name,
		content: '',
		onSubmit(component, value) {
		    console.log(value)
		}
	    });
        },`

**Comment by janmarkuslanger** [comment]
@metroidpam hey there, when do you render your component. Seems like the document.body isn´t available at the time.

**Comment by metroidpam** [comment]
I tried to render the component after clicking this button
![image](https://user-images.githubusercontent.com/4321428/91604282-ab6dde00-e96e-11ea-8160-cee36e6aac29.png)

The script where component is used : https://github.com/metroidpam/inventaire-front/blob/master/admin/scripts/admin.js
l 28

**Comment by janmarkuslanger** [comment]
I will give you a fix tomorrow. :)

Von meinem iPhone gesendet

**Comment by metroidpam** [comment]
No problem, thank you very much anyway for providing such a cool tool and helping out with any problem!

**Comment by janmarkuslanger** [comment]
@metroidpam please get the new attention.js file from the dist. This should for now for you. 
BTW: I refactor the whole lib at the moment.

Feel free to reopen the issue if the problem is still there.
