### ISSUE TITLE
Callbacks not triggered when accept with Confirm form

### ISSUE THREAD

**Issue by metroidpam** [janmarkuslanger/attention.js#4]
Hey ! I'm sorry to bother you again

![image](https://user-images.githubusercontent.com/4321428/91704872-733bea80-eb7c-11ea-84bf-2c84cc42cae5.png)

I wanted to create a Confirm component but when I press 'accept', onAccept is not triggered :/ (I put a console.log to make sure if it fit well or not)

Thanks again for the work you do!

**Comment by janmarkuslanger** [comment]
@metroidpam you´re not bothering me. I am happy that you found some bugs. I will look at this after work. A fix is coming later today :)

**Comment by metroidpam** [comment]
Thanks for all !

**Comment by janmarkuslanger** [comment]
@metroidpam can you send me the file where you included the code?

**Comment by metroidpam** [comment]
https://github.com/metroidpam/inventaire-front/blob/master/admin/scripts/admin.js

**Comment by janmarkuslanger** [comment]
@metroidpam thank you very much. I am sorry I could not fix that today. Tomorrow you have your fix!

**Comment by metroidpam** [comment]
Ok, no problem !

**Comment by janmarkuslanger** [comment]
@metroidpam I am working on it. Sorry

**Comment by janmarkuslanger** [comment]
@metroidpam my docu is too bad :D I am sorry `onAccept` is wrong you need to use `onConfirm`. Feel free to reopen if there is still an issue after changing the method name
