### ISSUE TITLE
No promises, just callbacks.

### ISSUE THREAD

**Issue by Danroyal001** [janmarkuslanger/attention.js#6]
Could you please extend the library to use promises, and not just callbacks?
Thanks.

**Comment by ShadowNoxX** [comment]
How do I make it yield execution until I submit

**Comment by janmarkuslanger** [comment]
Hi, @Danroyal001  I will take a look at this today :)

**Comment by Danroyal001** [comment]
@janmarkuslanger Ok,
Thanks

**Comment by Danroyal001** [comment]
@janmarkuslanger,
Also, can you reduce the css transition duration a little bit, it takes so much time, 0.2 seconds will be fine.
Thanks.

**Comment by janmarkuslanger** [comment]
@Danroyal001  pls create a new issue for this

**Comment by Danroyal001** [comment]
@janmarkuslanger 

> @Danroyal001 pls create a new issue for this

ok, I will

**Comment by janmarkuslanger** [comment]
@Danroyal001 hey there, sorry for the late response. I dont have time to take a look at this at the moment. Feel free to create a pull request with your feature request. 

In the future I want to refactor the whole base into typescript.
